In [1]:
import numpy as np

1. Create a null vector of size 10 but the fifth value which is 1.

In [2]:
null_vector=np.zeros(10,dtype=int)
null_vector[4]=1

In [3]:
print(null_vector)

[0 0 0 0 1 0 0 0 0 0]


2. Create a vector with values ranging from 10 to 49.

In [4]:
vector_ranging= np.arange(10,50)

In [5]:
print(vector_ranging)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


3. Create a 3x3 matrix with values ranging from 0 to 8

In [6]:
matrix=np.arange(0,9).reshape(3,3)

In [7]:
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [8]:
orignal_array=np.array([1,2,0,0,4,0])
n_array=np.nonzero(orignal_array==0)

In [9]:
print(n_array)

(array([2, 3, 5], dtype=int64),)


5. Create a 10x10 array with random values and find the minimum and maximum values.

In [10]:
rand_array=np.random.random((10,10))

In [11]:
print("The Minimum Value of Random Array :",rand_array.min())
print("The Maximum Value of Random Array :",rand_array.max())

The Minimum Value of Random Array : 0.0037312748071779422
The Maximum Value of Random Array : 0.9963346530499669


6. Create a random vector of size 30 and find the mean value.

In [19]:
rand_aaray=np.random.random(30)


In [20]:
print("The Mean Value Of Random Vector",rand_array.mean())

The Mean Value Of Random Vector 0.5108609306080487
